import { type Metadata } from "next";
import { ClerkProvider, ClerkLoaded, ClerkLoading } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LoadingScreen from "@/components/loadingScreen";

// layout.tsx
import { Inter, Orbitron, Saira_Stencil_One } from "next/font/google";

const sairaStencil = Saira_Stencil_One({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-saira",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const orbitron = Orbitron({
  subsets: ["latin"],
  variable: "--font-orbitron",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "D3pass",
  description: "Generated by create next app",
  generator: "Next.js",
  manifest: "/manifest.json",
  keywords: ["D3pass", "Next.js", "PWA"],
  authors: [{ name: "D3pass", url: "https://d3pass.com" }],
  creator: "D3pass",
  viewport:
    "minimum-scale=1.0, initial-scale=1.0, width=device-width, shrink-to-fit=no, viewport-fit=cover",
  icons: [
    {
      rel: "apple-touch-icon",
      url: "icons/0ass-512.png",
    },
    {
      rel: "icon",
      url: "icons/0ass-512.png",
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
        variables: {
          colorBackground: "#081238", // ← new background color
          colorText: "#E5E7EB", // soft light gray
          colorPrimary: "#8b5cf6", // vibrant violet
        },
        elements: {
          card: "bg-[#121A39]/90 backdrop-blur-xl border border-white/10 shadow-xl rounded-xl",
          headerTitle: "text-white font-semibold",
          formFieldInput:
            "bg-gray-900 text-white border-white/20 rounded-lg focus:ring-purple-600",
          formFieldLabel: "text-gray-300",
          formFieldErrorText: "text-red-500",
          formButtonPrimary:
            "bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-500 hover:to-purple-500 text-white font-semibold px-4 py-2 rounded-lg transition",
          footerActionLink: "text-purple-400 hover:text-purple-300",
          dividerText: "text-gray-400",
          socialButtonsBlockButton:
            "bg-gray-800 hover:bg-gray-700 text-white border border-white/10 rounded-lg",
          userButtonPopoverCard:
            "bg-[#121A39]/90 backdrop-blur-md border border-white/10 shadow-lg rounded-xl",
          userButtonPopoverOverlay: "bg-black/70 backdrop-blur-sm",
          userButtonPopoverActionButton:
            "hover:bg-gray-800 text-gray-300 hover:text-white transition",
          userButtonPopoverFooter: "bg-[#121A39]/80 border-t border-white/10",
        },
      }}
    >
      <html
        lang="en"
        className={`${sairaStencil.variable} ${inter.variable} ${orbitron.variable}`}
      >
        <head>
          <meta name="theme-color" content="#000000" />
          <link
            href="https://cdn.jsdelivr.net/npm/remixicon@4.1.0/fonts/remixicon.css"
            rel="stylesheet"
          />
          <link rel="manifest" href="/manifest.json" />
          <link rel="apple-touch-icon" href="/icons/0ass-512.png" />
          <link rel="icon" href="/icons/0ass-512.png" />
        </head>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ClerkLoading>
            <LoadingScreen />
          </ClerkLoading>
          <ClerkLoaded>{children}</ClerkLoaded>
        </body>
      </html>
    </ClerkProvider>
  );
}
